- name: install
  get_url: >
    dest={{ devopslab_bin }}/docker-compose
    url=https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64
    validate_certs=no
    mode=755
